#####################
### LOOK AND FEEL ###
#####################
general {
    border_size = 5
    col.active_border = rgb(ff00ff) rgb(00ffff) rgb(ffff00) 45deg
    col.inactive_border = rgba(88888888)
    
    resize_corner = 1
    extend_border_grab_area = 15
}


# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    rounding = 10
    active_opacity = 1.0
    inactive_opacity = 1.0


    # https://wiki.hyprland.org/Configuring/Variables/#blur
    blur {
        enabled = true
        passes = 3
        size = 5
        contrast = 1.2
        brightness = 1.2
        noise = 0.01
        vibrancy = 0.5
        vibrancy_darkness = 0.5
    }
}

animations {
    enabled = true
    bezier = rotate, 0.5, 0.9, 0.1, 1.0
    animation = borderangle, 1, 50, rotate, loop
}

misc {
    animate_manual_resizes = true
    animate_mouse_windowdragging = true
    enable_swallow = true
    swallow_regex = ^(kitty)$
}